(function( global ) {
  var emojify = (function() {

    // Get DOM as local variable for simplicity's sake
    var document = global.window.document;

    return {
      // This is some boolean property
      bool: true,
      // Some string value
      string: "a string",
      // An array property
      array: [ 1, 2, 3, 4 ],
      // An object property
      object: {
        lang: "en-Us"
      },
      config: function() {
      },
      run: function() {

        var persons = [
          [/:bowtie:/g, "<div class='emoji bowtie'></div>"],
          [/:smile:/g, "<div class='emoji smile' /></div>"],
          [/:laughing:/g, "<div class='emoji laughing' /></div>"],
          [/:blush:|\:-\)|\:\)/g, "<div class='emoji blush' /></div>"],
          [/:relaxed:|:-*\$/g, "<div class='emoji relaxed' /></div>"],
          [/:smirk:|\:]|;-*]/g, "<div class='emoji smirk' /></div>"],
          [/:heart_eyes:/g, "<div class='emoji heart_eyes'></div>"],
          [/:kissing_heart:|:-*\*/g, "<div class='emoji kissing_heart' /></div>"],
          [/:kissing_closed_eyes:/g, "<div class='emoji kissing_closed_eyes' /></div>"],
          [/:flushed:|:-*\|/g, "<div class='emoji flushed' /></div>"],
          [/:relieved:/g, "<div class='emoji relieved' /></div>"],
          [/:satisfied:/g, "<div class='emoji satisfied' /></div>"],
          [/:grin:/g, "<div class='emoji grin' /></div>"],
          [/:wink:|;-*\)/g, "<div class='emoji wink' /></div>"],
          [/:wink2:/g, "<div class='emoji wink2' /></div>"],
          [/:stuck_out_tongue_closed_eyes:|xd/gi, "<div class='emoji stuck_out_tongue_closed_eyes' /></div>"],
          [/:grinning:/g, "<div class='emoji grinning' /></div>"],
          [/:kissing:/g, "<div class='emoji kissing' /></div>"],
          [/:kissing_smiling_eyes:/g, "<div class='emoji kissing_smiling_eyes' /></div>"],
          [/:stuck_out_tongue:/g, "<div class='emoji stuck_out_tongue' /></div>"],
          [/:sleeping:/g, "<div class='emoji sleeping' /></div>"],
          [/:worried:/g, "<div class='emoji worried' /></div>"],
          [/:frowning:/g, "<div class='emoji frowning' /></div>"],
          [/:anguished:/g, "<div class='emoji anguished' /></div>"],
          [/:open_mouth:/g, "<div class='emoji open_mouth' /></div>"],
          [/:grimacing:/g, "<div class='emoji grimacing' /></div>"],
          [/:confused:/g, "<div class='emoji confused' /></div>"],
          [/:hushed:/g, "<div class='emoji hushed' /></div>"],
          [/:expressionless:/g, "<div class='emoji expressionless' /></div>"],
          [/:unamused:/g, "<div class='emoji unamused' /></div>"],
          [/:sweat_smile:/g, "<div class='emoji sweat_smile' /></div>"],          
          [/:sweat:/g, "<div class='emoji sweat' /></div>"],
          [/:weary:/g, "<div class='emoji weary' /></div>"],
          [/:pensive:|:-*\//g, "<div class='emoji pensive' /></div>"],
          [/:disappointed:|:(-*\()/g, "<div class='emoji disappointed' /></div>"],
          [/:fearful:/g, "<div class='emoji fearful' /></div>"],
          [/:cold_sweat:/g, "<div class='emoji cold_sweat' /></div>"],
          [/:persevere:/g, "<div class='emoji persevere' /></div>"],
          [/:cry:/g, "<div class='emoji cry' /></div>"],
          [/:sob:|:'-*\(/g, "<div class='emoji sob' /></div>"],
          [/:joy:/g, "<div class='emoji joy' /></div>"],
          [/:astonished:/g, "<div class='emoji astonished' /></div>"],
          [/:neckbeard:/g, "<div class='emoji neckbeard' /></div>"],
          [/:tired_face:/g, "<div class='emoji tired_face' /></div>"],
          [/:angry:/g, "<div class='emoji angry' /></div>"],
          [/:rage:|:(-*(\[|\|\||@))/g, "<div class='emoji rage' /></div>"],
          [/:triumph:/g, "<div class='emoji triumph' /></div>"],
          [/:sleepy:/g, "<div class='emoji sleepy' /></div>"],
          [/:yum:/g, "<div class='emoji yum' /></div>"],
          [/:mask:|:-*x/gi, "<div class='emoji mask' /></div>"],
          [/:sunglasses:/g, "<div class='emoji sunglasses' /></div>"],
          [/:dizzy_face:/g, "<div class='emoji dizzy_face' /></div>"],
          [/:imp:/g, "<div class='emoji imp' /></div>"],
          [/:smiling_imp:/g, "<div class='emoji smiling_imp' /></div>"],
          [/:neutral_face:/g, "<div class='emoji neutral_face' /></div>"],
          [/:no_mouth:/g, "<div class='emoji no_mouth' /></div>"],
          [/:innocent:/g, "<div class='emoji innocent' /></div>"],
          [/:alien:/g, "<div class='emoji alien' /></div>"],
          [/:yellow_heart:/g, "<div class='emoji yellow_heart' /></div>"],
          [/:blue_heart:/g, "<div class='emoji blue_heart' /></div>"],
          [/:purple_heart:/g, "<div class='emoji purple_heart' /></div>"],
          [/:heart:|&lt;3/g, "<div class='emoji heart'></div>"],
          [/:green_heart:/g, "<div class='emoji green_heart' /></div>"],
          [/:broken_heart:|&lt;\/3/g, "<div class='emoji broken_heart' /></div>"],
          [/:heartbeat:/g, "<div class='emoji heartbeat'></div>"],
          [/:heartpulse:/g, "<div class='emoji heartpulse'></div>"],
          [/:two_hearts:/g, "<div class='emoji two_hearts' /></div>"],
          [/:revolving_hearts:/g, "<div class='emoji revolving_hearts' /></div>"],
          [/:cupid:/g, "<div class='emoji cupid' /></div>"],
          [/:sparkling_heart:/g, "<div class='emoji sparkling_heart' /></div>"],
          [/:sparkles:/g, "<div class='emoji sparkles' /></div>"],
          [/:star:/g, "<div class='emoji star' /></div>"],
          [/:star2:/g, "<div class='emoji star2' /></div>"],
          [/:dizzy:/g, "<div class='emoji dizzy' /></div>"],
          [/:boom:/g, "<div class='emoji boom' /></div>"],
          [/:collision:/g, "<div class='emoji collision' /></div>"],
          [/:anger:/g, "<div class='emoji anger' /></div>"],
          [/:exclamation:/g, "<div class='emoji exclamation' /></div>"],
          [/:question:/g, "<div class='emoji question' /></div>"],
          [/:grey_exclamation:/g, "<div class='emoji grey_exclamation' /></div>"],
          [/:grey_question:/g, "<div class='emoji grey_question' /></div>"],
          [/:zzz:/g, "<div class='emoji zzz' /></div>"],
          [/:dash:/g, "<div class='emoji dash' /></div>"],
          [/:sweat_drops:/g, "<div class='emoji sweat_drops' /></div>"],
          [/:notes:/g, "<div class='emoji notes' /></div>"],
          [/:musical_note:/g, "<div class='emoji musical_note' /></div>"],
          [/:fire:/g, "<div class='emoji fire' /></div>"],
          [/:hankey:/g, "<div class='emoji hankey'></div>"],
          [/:poop:/g, "<div class='emoji poop' /></div>"],
          [/:shit:/g, "<div class='emoji shit' /></div>"],
          [/:thumbsup:|:\+1:/g, "<div class='emoji thumbsup' /></div>"],
          [/:thumbsdown:|:-1:/g, "<div class='emoji thumbsdown' /></div>"],
          [/:ok_hand:/g, "<div class='emoji ok_hand' /></div>"],
          [/:punch:/g, "<div class='emoji punch' /></div>"],
          [/:facepunch:/g, "<div class='emoji facepunch' /></div>"],
          [/:fist:/g, "<div class='emoji fist' /></div>"],
          [/:v:/g, "<div class='emoji v' /></div>"],
          [/:wave:/g, "<div class='emoji wave' /></div>"],
          [/:hand:/g, "<div class='emoji hand'></div>"],
          [/:open_hands:/g, "<div class='emoji open_hands' /></div>"],
          [/:point_up:/g, "<div class='emoji point_up' /></div>"],
          [/:point_down:/g, "<div class='emoji point_down' /></div>"],
          [/:point_left:/g, "<div class='emoji point_left' /></div>"],
          [/:point_right:/g, "<div class='emoji point_right' /></div>"],
          [/:raised_hands:/g, "<div class='emoji raised_hands' /></div>"],
          [/:pray:/g, "<div class='emoji pray' /></div>"],
          [/:point_up_2:/g, "<div class='emoji point_up_2' /></div>"],
          [/:clap:/g, "<div class='emoji clap' /></div>"],
          [/:muscle:/g, "<div class='emoji muscle' /></div>"],
          [/:metal:/g, "<div class='emoji metal' /></div>"],
          [/:walking:/g, "<div class='emoji walking' /></div>"],
          [/:runner:/g, "<div class='emoji runner' /></div>"],
          [/:running:/g, "<div class='emoji running' /></div>"],
          [/:couple:/g, "<div class='emoji couple' /></div>"],
          [/:family:/g, "<div class='emoji family' /></div>"],
          [/:two_men_holding_hands:/g, "<div class='emoji two_men_holding_hands' /></div>"],
          [/:two_women_holding_hands:/g, "<div class='emoji two_women_holding_hands' /></div>"],
          [/:dancer:/g, "<div class='emoji dancer' /></div>"],
          [/:dancers:/g, "<div class='emoji dancers' /></div>"],
          [/:ok_woman:/g, "<div class='emoji ok_woman' /></div>"],
          [/:no_good:/g, "<div class='emoji no_good' /></div>"],
          [/:information_desk_person:/g, "<div class='emoji information_desk_person' /></div>"],
          [/:raised_hand:/g, "<div class='emoji raised_hand' /></div>"],
          [/:bride_with_veil:/g, "<div class='emoji bride_with_veil' /></div>"],
          [/:person_with_pouting_face:/g, "<div class='emoji person_with_pouting_face' /></div>"],
          [/:person_frowning:/g, "<div class='emoji person_frowning' /></div>"],
          [/:bow:/g, "<div class='emoji bow' /></div>"],
          [/:couplekiss:/g, "<div class='emoji couplekiss' /></div>"],
          [/:couple_with_heart:/g, "<div class='emoji couple_with_heart' /></div>"],
          [/:massage:/g, "<div class='emoji massage' /></div>"],
          [/:haircut:/g, "<div class='emoji haircut' /></div>"],
          [/:nail_care:/g, "<div class='emoji nail_care' /></div>"],
          [/:boy:/g, "<div class='emoji boy' /></div>"],
          [/:girl:/g, "<div class='emoji girl' /></div>"],
          [/:woman:/g, "<div class='emoji woman' /></div>"],
          [/:man:/g, "<div class='emoji man' /></div>"],
          [/:baby:/g, "<div class='emoji baby' /></div>"],
          [/:older_woman:/g, "<div class='emoji older_woman' /></div>"],
          [/:older_man:/g, "<div class='emoji older_man' /></div>"],
          [/:person_with_blond_hair:/g, "<div class='emoji person_with_blond_hair' /></div>"],
          [/:man_with_gua_pi_mao:/g, "<div class='emoji man_with_gua_pi_mao' /></div>"],
          [/:man_with_turban:/g, "<div class='emoji man_with_turban' /></div>"],
          [/:construction_worker:/g, "<div class='emoji construction_worker' /></div>"],
          [/:cop:/g, "<div class='emoji cop' /></div>"],
          [/:angel:/g, "<div class='emoji angel' /></div>"],
          [/:princess:/g, "<div class='emoji princess' /></div>"],
          [/:smiley_cat:/g, "<div class='emoji smiley_cat' /></div>"],
          [/:smile_cat:/g, "<div class='emoji smile_cat' /></div>"],
          [/:heart_eyes_cat:/g, "<div class='emoji heart_eyes_cat'></div>"],
          [/:kissing_cat:/g, "<div class='emoji kissing_cat' /></div>"],
          [/:smirk_cat:/g, "<div class='emoji smirk_cat' /></div>"],
          [/:scream_cat:/g, "<div class='emoji scream_cat' /></div>"],
          [/:crying_cat_face:/g, "<div class='emoji crying_cat_face' /></div>"],
          [/:joy_cat:/g, "<div class='emoji joy_cat' /></div>"],
          [/:pouting_cat:/g, "<div class='emoji pouting_cat' /></div>"],
          [/:japanese_ogre:/g, "<div class='emoji japanese_ogre' /></div>"],
          [/:japanese_goblin:/g, "<div class='emoji japanese_goblin' /></div>"],
          [/:see_no_evil:/g, "<div class='emoji see_no_evil' /></div>"],
          [/:hear_no_evil:/g, "<div class='emoji hear_no_evil'></div>"],
          [/:speak_no_evil:/g, "<div class='emoji speak_no_evil' /></div>"],
          [/:guardsman:/g, "<div class='emoji guardsman' /></div>"],
          [/:skull:/g, "<div class='emoji skull' /></div>"],
          [/:feet:/g, "<div class='emoji feet' /></div>"],
          [/:lips:/g, "<div class='emoji lips' /></div>"],
          [/:kiss:/g, "<div class='emoji kiss' /></div>"],
          [/:droplet:/g, "<div class='emoji droplet' /></div>"],
          [/:ear:/g, "<div class='emoji ear' /></div>"],
          [/:eyes:/g, "<div class='emoji eyes' /></div>"],
          [/:nose:/g, "<div class='emoji nose' /></div>"],
          [/:tongue:/g, "<div class='emoji tongue' /></div>"],
          [/:love_letter:/g, "<div class='emoji love_letter' /></div>"],
          [/:bust_in_silhouette:/g, "<div class='emoji bust_in_silhouette' /></div>"],
          [/:busts_in_silhouette:/g, "<div class='emoji busts_in_silhouette' /></div>"],
          [/:speech_balloon:/g, "<div class='emoji speech_balloon' /></div>"],
          [/:thought_balloon:/g, "<div class='emoji thought_balloon' /></div>"],
          [/:feelsgood:/g, "<div class='emoji feelsgood' /></div>"],
          [/:finnadie:/g, "<div class='emoji finnadie' /></div>"],
          [/:goberserk:/g, "<div class='emoji goberserk' /></div>"],
          [/:godmode:/g, "<div class='emoji godmode' /></div>"],
          [/:hurtrealbad:/g, "<div class='emoji hurtrealbad' /></div>"],
          [/:rage1:/g, "<div class='emoji rage1' /></div>"],
          [/:rage2:/g, "<div class='emoji rage2' /></div>"],
          [/:rage3:/g, "<div class='emoji rage3' /></div>"],
          [/:rage4:/g, "<div class='emoji rage4' /></div>"],
          [/:suspect:/g, "<div class='emoji suspect' /></div>"],
          [/:trollface:/g, "<div class='emoji trollface' /></div>"],

          // Moving problematic matches to the bottom
          [/:smiley:|;D|:-*D/gi, "<div class='emoji smiley' /></div>"],
          [/:scream:|\:-*o/gi, "<div class='emoji scream' /></div>"],
          [/:stuck_out_tongue_winking_eye:|:-*p/gi, "<div class='emoji stuck_out_tongue_winking_eye' /></div>"],
          [/:confounded:|:-*s/gi, "<div class='emoji confounded' /></div>"]
        ], r;
        
        while ((r = persons.shift()) && (document.body.innerHTML = String.prototype.replace.apply(document.body.innerHTML, r))) {}

        return;
      }
    };
  })();

  global.emojify = emojify;

})( this );